import { useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'nl' | 'pl' | 'ru' | 'zh' | 'ja' | 'ko' | 'ar' | 'hi' | 'th' | 'vi';

// Map browser language codes to our supported languages
const languageMap: Record<string, SupportedLanguage> = {
  'en': 'en', 'en-US': 'en', 'en-GB': 'en', 'en-AU': 'en',
  'es': 'es', 'es-ES': 'es', 'es-MX': 'es', 'es-AR': 'es',
  'fr': 'fr', 'fr-FR': 'fr', 'fr-CA': 'fr',
  'de': 'de', 'de-DE': 'de', 'de-AT': 'de', 'de-CH': 'de',
  'it': 'it', 'it-IT': 'it',
  'pt': 'pt', 'pt-BR': 'pt', 'pt-PT': 'pt',
  'nl': 'nl', 'nl-NL': 'nl', 'nl-BE': 'nl',
  'pl': 'pl', 'pl-PL': 'pl',
  'ru': 'ru', 'ru-RU': 'ru',
  'zh': 'zh', 'zh-CN': 'zh', 'zh-TW': 'zh', 'zh-HK': 'zh',
  'ja': 'ja', 'ja-JP': 'ja',
  'ko': 'ko', 'ko-KR': 'ko',
  'ar': 'ar', 'ar-SA': 'ar', 'ar-EG': 'ar',
  'hi': 'hi', 'hi-IN': 'hi',
  'th': 'th', 'th-TH': 'th',
  'vi': 'vi', 'vi-VN': 'vi',
};

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Loading & Errors
    loading: 'Loading...',
    invalidLink: 'Invalid review link. Please use a valid location link.',
    locationNotFound: 'Location not found',
    loadFailed: 'Failed to load review form',
    
    // Check-in
    checkInTitle: 'Welcome to {businessName}!',
    checkInDescription: 'Quick check-in - we\'ll send you a review link after your visit',
    checkInEmail: 'Email *',
    checkInEmailPlaceholder: 'your@email.com',
    checkInName: 'Name (optional)',
    checkInNamePlaceholder: 'Your name',
    checkInButton: 'Check In',
    checkingIn: 'Checking in...',
    checkInNote: 'We\'ll email you a link to share your experience after your visit. No spam, just one review request.',
    
    // Check-in Complete
    checkInCompleteTitle: 'Thanks for checking in!',
    checkInCompleteMessage: 'We\'ll send you a link to share your experience later today.',
    checkInCompleteTiming: 'Review link will be sent in ~{hours} hours',
    checkInCompleteEnjoy: 'Enjoy your visit! ✨',
    alreadyCheckedIn: 'Already checked in!',
    alreadyCheckedInMessage: 'You\'ve already checked in today. We\'ll send your review link soon!',
    
    // Feedback Submitted
    feedbackSubmittedTitle: 'Thank you for your feedback!',
    feedbackSubmittedMessage: 'Your feedback helps us improve. We appreciate you taking the time to share your experience with us.',
    feedbackSubmittedNote: 'Our team will review your feedback and may reach out if needed.',
    
    // Review Form
    howWasExperience: 'How was your experience?',
    tapToRate: 'Tap to rate',
    ratingExcellent: 'Excellent! 🎉',
    ratingGreat: 'Great! 👍',
    ratingGood: 'Good 😊',
    ratingFair: 'Fair 😐',
    ratingPoor: 'Poor 😔',
    
    // Characteristics
    whatStoodOut: 'What stood out?',
    
    // Comment Styles
    friendly: 'friendly',
    professional: 'professional',
    enthusiastic: 'enthusiastic',
    
    // Review Generation
    yourReview: 'Your review',
    aiGenerated: 'AI-generated',
    generatingReview: 'Generating your review...',
    reviewPlaceholder: 'Your review will appear here...',
    regenerateReview: 'Regenerate Review',
    regenerating: 'Regenerating...',
    
    // Actions
    copyAndPost: 'Copy & Post to Google',
    copiedPaste: 'Copied! Now paste in Google',
    pasteHint: 'Long-press in Google\'s text box, then tap "Paste"',
    submitFeedback: 'Submit Feedback',
    submitting: 'Submitting...',
    feedbackNote: 'Your feedback will help us improve our service',
    emailOptional: 'your@email.com (optional - for thank you)',
    
    // Navigation
    back: 'Back',
    next: 'Next',
    generating: 'Generating...',
    
    // Toasts
    selectRating: 'Please select a rating',
    selectCharacteristics: 'Select characteristics',
    selectCharacteristicsDesc: 'Please select at least one aspect to highlight in your review',
    commentGenerated: 'Comment generated!',
    commentGeneratedDesc: 'Feel free to edit it before copying',
    generationFailed: 'Generation failed',
    generationFailedDesc: 'Please try again or write your own comment',
    noReviewToCopy: 'No review to copy',
    noReviewToCopyDesc: 'Please generate or write a review first',
    noGoogleLink: 'No Google Review link',
    noGoogleLinkDesc: 'This business hasn\'t set up their Google Review link yet',
    reviewCopied: 'Review copied!',
    reviewCopiedDesc: 'Paste it in the Google form that just opened',
    copyFailed: 'Couldn\'t copy automatically',
    copyFailedDesc: 'Please copy the review text manually and paste it in Google',
    feedbackSubmitted: 'Feedback submitted',
    feedbackSubmittedDesc: 'Thank you for sharing your experience',
    submissionFailed: 'Submission failed',
    submissionFailedDesc: 'Please try again',
    checkInFailed: 'Check-in failed',
    checkInFailedDesc: 'Please try again',
  },
  
  es: {
    loading: 'Cargando...',
    invalidLink: 'Enlace de reseña inválido. Por favor use un enlace válido.',
    locationNotFound: 'Ubicación no encontrada',
    loadFailed: 'Error al cargar el formulario',
    checkInTitle: '¡Bienvenido a {businessName}!',
    checkInDescription: 'Registro rápido - te enviaremos un enlace para tu reseña después de tu visita',
    checkInEmail: 'Correo electrónico *',
    checkInEmailPlaceholder: 'tu@correo.com',
    checkInName: 'Nombre (opcional)',
    checkInNamePlaceholder: 'Tu nombre',
    checkInButton: 'Registrarse',
    checkingIn: 'Registrando...',
    checkInNote: 'Te enviaremos un enlace por correo para compartir tu experiencia. Sin spam, solo una solicitud de reseña.',
    checkInCompleteTitle: '¡Gracias por registrarte!',
    checkInCompleteMessage: 'Te enviaremos un enlace para compartir tu experiencia más tarde.',
    checkInCompleteTiming: 'El enlace se enviará en ~{hours} horas',
    checkInCompleteEnjoy: '¡Disfruta tu visita! ✨',
    alreadyCheckedIn: '¡Ya registrado!',
    alreadyCheckedInMessage: '¡Ya te registraste hoy. Te enviaremos el enlace pronto!',
    feedbackSubmittedTitle: '¡Gracias por tu opinión!',
    feedbackSubmittedMessage: 'Tu opinión nos ayuda a mejorar. Agradecemos que compartas tu experiencia.',
    feedbackSubmittedNote: 'Nuestro equipo revisará tu opinión y puede contactarte si es necesario.',
    howWasExperience: '¿Cómo fue tu experiencia?',
    tapToRate: 'Toca para calificar',
    ratingExcellent: '¡Excelente! 🎉',
    ratingGreat: '¡Muy bien! 👍',
    ratingGood: 'Bien 😊',
    ratingFair: 'Regular 😐',
    ratingPoor: 'Malo 😔',
    whatStoodOut: '¿Qué destacó?',
    friendly: 'amigable',
    professional: 'profesional',
    enthusiastic: 'entusiasta',
    yourReview: 'Tu reseña',
    aiGenerated: 'Generado por IA',
    generatingReview: 'Generando tu reseña...',
    reviewPlaceholder: 'Tu reseña aparecerá aquí...',
    regenerateReview: 'Regenerar Reseña',
    regenerating: 'Regenerando...',
    copyAndPost: 'Copiar y Publicar en Google',
    copiedPaste: '¡Copiado! Ahora pega en Google',
    pasteHint: 'Mantén presionado en el cuadro de texto de Google, luego toca "Pegar"',
    submitFeedback: 'Enviar Opinión',
    submitting: 'Enviando...',
    feedbackNote: 'Tu opinión nos ayudará a mejorar nuestro servicio',
    emailOptional: 'tu@correo.com (opcional)',
    back: 'Atrás',
    next: 'Siguiente',
    generating: 'Generando...',
    selectRating: 'Por favor selecciona una calificación',
    selectCharacteristics: 'Selecciona características',
    selectCharacteristicsDesc: 'Por favor selecciona al menos un aspecto para destacar',
    commentGenerated: '¡Comentario generado!',
    commentGeneratedDesc: 'Puedes editarlo antes de copiar',
    generationFailed: 'Error al generar',
    generationFailedDesc: 'Intenta de nuevo o escribe tu propio comentario',
    noReviewToCopy: 'Sin reseña para copiar',
    noReviewToCopyDesc: 'Por favor genera o escribe una reseña primero',
    noGoogleLink: 'Sin enlace de Google Review',
    noGoogleLinkDesc: 'Este negocio no ha configurado su enlace de Google Review',
    reviewCopied: '¡Reseña copiada!',
    reviewCopiedDesc: 'Pégala en el formulario de Google',
    copyFailed: 'No se pudo copiar automáticamente',
    copyFailedDesc: 'Por favor copia el texto manualmente y pégalo en Google',
    feedbackSubmitted: 'Opinión enviada',
    feedbackSubmittedDesc: 'Gracias por compartir tu experiencia',
    submissionFailed: 'Error al enviar',
    submissionFailedDesc: 'Por favor intenta de nuevo',
    checkInFailed: 'Error al registrarse',
    checkInFailedDesc: 'Por favor intenta de nuevo',
  },
  
  fr: {
    loading: 'Chargement...',
    invalidLink: 'Lien invalide. Veuillez utiliser un lien valide.',
    locationNotFound: 'Emplacement non trouvé',
    loadFailed: 'Échec du chargement',
    checkInTitle: 'Bienvenue chez {businessName}!',
    checkInDescription: 'Enregistrement rapide - nous vous enverrons un lien pour votre avis après votre visite',
    checkInEmail: 'Email *',
    checkInEmailPlaceholder: 'votre@email.com',
    checkInName: 'Nom (optionnel)',
    checkInNamePlaceholder: 'Votre nom',
    checkInButton: 'S\'enregistrer',
    checkingIn: 'Enregistrement...',
    checkInNote: 'Nous vous enverrons un lien par email après votre visite. Pas de spam.',
    checkInCompleteTitle: 'Merci de vous être enregistré!',
    checkInCompleteMessage: 'Nous vous enverrons un lien pour partager votre expérience.',
    checkInCompleteTiming: 'Le lien sera envoyé dans ~{hours} heures',
    checkInCompleteEnjoy: 'Bonne visite! ✨',
    alreadyCheckedIn: 'Déjà enregistré!',
    alreadyCheckedInMessage: 'Vous êtes déjà enregistré aujourd\'hui.',
    feedbackSubmittedTitle: 'Merci pour votre avis!',
    feedbackSubmittedMessage: 'Votre avis nous aide à nous améliorer.',
    feedbackSubmittedNote: 'Notre équipe examinera votre avis.',
    howWasExperience: 'Comment était votre expérience?',
    tapToRate: 'Appuyez pour noter',
    ratingExcellent: 'Excellent! 🎉',
    ratingGreat: 'Très bien! 👍',
    ratingGood: 'Bien 😊',
    ratingFair: 'Moyen 😐',
    ratingPoor: 'Mauvais 😔',
    whatStoodOut: 'Qu\'est-ce qui s\'est démarqué?',
    friendly: 'amical',
    professional: 'professionnel',
    enthusiastic: 'enthousiaste',
    yourReview: 'Votre avis',
    aiGenerated: 'Généré par IA',
    generatingReview: 'Génération de votre avis...',
    reviewPlaceholder: 'Votre avis apparaîtra ici...',
    regenerateReview: 'Régénérer l\'avis',
    regenerating: 'Régénération...',
    copyAndPost: 'Copier et Publier sur Google',
    copiedPaste: 'Copié! Collez dans Google',
    pasteHint: 'Appuyez longuement dans Google, puis "Coller"',
    submitFeedback: 'Envoyer l\'avis',
    submitting: 'Envoi...',
    feedbackNote: 'Votre avis nous aidera à améliorer',
    emailOptional: 'votre@email.com (optionnel)',
    back: 'Retour',
    next: 'Suivant',
    generating: 'Génération...',
    selectRating: 'Veuillez sélectionner une note',
    selectCharacteristics: 'Sélectionnez des caractéristiques',
    selectCharacteristicsDesc: 'Veuillez sélectionner au moins un aspect',
    commentGenerated: 'Commentaire généré!',
    commentGeneratedDesc: 'Modifiez-le avant de copier',
    generationFailed: 'Échec de génération',
    generationFailedDesc: 'Réessayez ou écrivez votre propre commentaire',
    noReviewToCopy: 'Pas d\'avis à copier',
    noReviewToCopyDesc: 'Veuillez d\'abord générer ou écrire un avis',
    noGoogleLink: 'Pas de lien Google Review',
    noGoogleLinkDesc: 'Cette entreprise n\'a pas configuré son lien Google',
    reviewCopied: 'Avis copié!',
    reviewCopiedDesc: 'Collez-le dans le formulaire Google',
    copyFailed: 'Copie automatique échouée',
    copyFailedDesc: 'Copiez manuellement le texte',
    feedbackSubmitted: 'Avis envoyé',
    feedbackSubmittedDesc: 'Merci pour votre partage',
    submissionFailed: 'Échec de l\'envoi',
    submissionFailedDesc: 'Veuillez réessayer',
    checkInFailed: 'Échec de l\'enregistrement',
    checkInFailedDesc: 'Veuillez réessayer',
  },
  
  de: {
    loading: 'Laden...',
    invalidLink: 'Ungültiger Link. Bitte verwenden Sie einen gültigen Link.',
    locationNotFound: 'Standort nicht gefunden',
    loadFailed: 'Laden fehlgeschlagen',
    checkInTitle: 'Willkommen bei {businessName}!',
    checkInDescription: 'Schneller Check-in - wir senden Ihnen nach Ihrem Besuch einen Link',
    checkInEmail: 'E-Mail *',
    checkInEmailPlaceholder: 'ihre@email.com',
    checkInName: 'Name (optional)',
    checkInNamePlaceholder: 'Ihr Name',
    checkInButton: 'Einchecken',
    checkingIn: 'Einchecken...',
    checkInNote: 'Wir senden Ihnen einen Link per E-Mail. Kein Spam.',
    checkInCompleteTitle: 'Danke für das Einchecken!',
    checkInCompleteMessage: 'Wir senden Ihnen später einen Link.',
    checkInCompleteTiming: 'Link wird in ~{hours} Stunden gesendet',
    checkInCompleteEnjoy: 'Genießen Sie Ihren Besuch! ✨',
    alreadyCheckedIn: 'Bereits eingecheckt!',
    alreadyCheckedInMessage: 'Sie sind bereits eingecheckt.',
    feedbackSubmittedTitle: 'Danke für Ihr Feedback!',
    feedbackSubmittedMessage: 'Ihr Feedback hilft uns, uns zu verbessern.',
    feedbackSubmittedNote: 'Unser Team wird Ihr Feedback prüfen.',
    howWasExperience: 'Wie war Ihre Erfahrung?',
    tapToRate: 'Tippen zum Bewerten',
    ratingExcellent: 'Ausgezeichnet! 🎉',
    ratingGreat: 'Sehr gut! 👍',
    ratingGood: 'Gut 😊',
    ratingFair: 'Mittelmäßig 😐',
    ratingPoor: 'Schlecht 😔',
    whatStoodOut: 'Was hat sich abgehoben?',
    friendly: 'freundlich',
    professional: 'professionell',
    enthusiastic: 'enthusiastisch',
    yourReview: 'Ihre Bewertung',
    aiGenerated: 'KI-generiert',
    generatingReview: 'Bewertung wird generiert...',
    reviewPlaceholder: 'Ihre Bewertung erscheint hier...',
    regenerateReview: 'Neu generieren',
    regenerating: 'Regenerieren...',
    copyAndPost: 'Kopieren & auf Google posten',
    copiedPaste: 'Kopiert! Jetzt in Google einfügen',
    pasteHint: 'Lang drücken in Google, dann "Einfügen"',
    submitFeedback: 'Feedback senden',
    submitting: 'Wird gesendet...',
    feedbackNote: 'Ihr Feedback hilft uns',
    emailOptional: 'ihre@email.com (optional)',
    back: 'Zurück',
    next: 'Weiter',
    generating: 'Generieren...',
    selectRating: 'Bitte wählen Sie eine Bewertung',
    selectCharacteristics: 'Merkmale auswählen',
    selectCharacteristicsDesc: 'Bitte wählen Sie mindestens einen Aspekt',
    commentGenerated: 'Kommentar generiert!',
    commentGeneratedDesc: 'Sie können ihn vor dem Kopieren bearbeiten',
    generationFailed: 'Generierung fehlgeschlagen',
    generationFailedDesc: 'Versuchen Sie es erneut',
    noReviewToCopy: 'Keine Bewertung zum Kopieren',
    noReviewToCopyDesc: 'Bitte generieren Sie zuerst eine Bewertung',
    noGoogleLink: 'Kein Google-Link',
    noGoogleLinkDesc: 'Dieses Unternehmen hat keinen Google-Link eingerichtet',
    reviewCopied: 'Bewertung kopiert!',
    reviewCopiedDesc: 'Fügen Sie sie in Google ein',
    copyFailed: 'Automatisches Kopieren fehlgeschlagen',
    copyFailedDesc: 'Kopieren Sie den Text manuell',
    feedbackSubmitted: 'Feedback gesendet',
    feedbackSubmittedDesc: 'Danke fürs Teilen',
    submissionFailed: 'Senden fehlgeschlagen',
    submissionFailedDesc: 'Bitte erneut versuchen',
    checkInFailed: 'Check-in fehlgeschlagen',
    checkInFailedDesc: 'Bitte erneut versuchen',
  },
  
  it: {
    loading: 'Caricamento...',
    invalidLink: 'Link non valido. Usa un link valido.',
    locationNotFound: 'Posizione non trovata',
    loadFailed: 'Caricamento fallito',
    checkInTitle: 'Benvenuto a {businessName}!',
    checkInDescription: 'Check-in rapido - ti invieremo un link dopo la visita',
    checkInEmail: 'Email *',
    checkInEmailPlaceholder: 'tua@email.com',
    checkInName: 'Nome (opzionale)',
    checkInNamePlaceholder: 'Il tuo nome',
    checkInButton: 'Check-in',
    checkingIn: 'Check-in in corso...',
    checkInNote: 'Ti invieremo un link via email dopo la visita.',
    checkInCompleteTitle: 'Grazie per il check-in!',
    checkInCompleteMessage: 'Ti invieremo un link per condividere la tua esperienza.',
    checkInCompleteTiming: 'Il link verrà inviato tra ~{hours} ore',
    checkInCompleteEnjoy: 'Buona visita! ✨',
    alreadyCheckedIn: 'Già registrato!',
    alreadyCheckedInMessage: 'Hai già fatto il check-in oggi.',
    feedbackSubmittedTitle: 'Grazie per il tuo feedback!',
    feedbackSubmittedMessage: 'Il tuo feedback ci aiuta a migliorare.',
    feedbackSubmittedNote: 'Il nostro team esaminerà il tuo feedback.',
    howWasExperience: 'Com\'è stata la tua esperienza?',
    tapToRate: 'Tocca per valutare',
    ratingExcellent: 'Eccellente! 🎉',
    ratingGreat: 'Ottimo! 👍',
    ratingGood: 'Buono 😊',
    ratingFair: 'Discreto 😐',
    ratingPoor: 'Scarso 😔',
    whatStoodOut: 'Cosa ti ha colpito?',
    friendly: 'amichevole',
    professional: 'professionale',
    enthusiastic: 'entusiasta',
    yourReview: 'La tua recensione',
    aiGenerated: 'Generato da IA',
    generatingReview: 'Generazione recensione...',
    reviewPlaceholder: 'La tua recensione apparirà qui...',
    regenerateReview: 'Rigenera Recensione',
    regenerating: 'Rigenerazione...',
    copyAndPost: 'Copia e Pubblica su Google',
    copiedPaste: 'Copiato! Incolla in Google',
    pasteHint: 'Premi a lungo in Google, poi "Incolla"',
    submitFeedback: 'Invia Feedback',
    submitting: 'Invio...',
    feedbackNote: 'Il tuo feedback ci aiuterà a migliorare',
    emailOptional: 'tua@email.com (opzionale)',
    back: 'Indietro',
    next: 'Avanti',
    generating: 'Generazione...',
    selectRating: 'Seleziona una valutazione',
    selectCharacteristics: 'Seleziona caratteristiche',
    selectCharacteristicsDesc: 'Seleziona almeno un aspetto',
    commentGenerated: 'Commento generato!',
    commentGeneratedDesc: 'Puoi modificarlo prima di copiare',
    generationFailed: 'Generazione fallita',
    generationFailedDesc: 'Riprova',
    noReviewToCopy: 'Nessuna recensione da copiare',
    noReviewToCopyDesc: 'Prima genera o scrivi una recensione',
    noGoogleLink: 'Nessun link Google',
    noGoogleLinkDesc: 'Questa attività non ha un link Google',
    reviewCopied: 'Recensione copiata!',
    reviewCopiedDesc: 'Incollala in Google',
    copyFailed: 'Copia automatica fallita',
    copyFailedDesc: 'Copia manualmente il testo',
    feedbackSubmitted: 'Feedback inviato',
    feedbackSubmittedDesc: 'Grazie per la condivisione',
    submissionFailed: 'Invio fallito',
    submissionFailedDesc: 'Riprova',
    checkInFailed: 'Check-in fallito',
    checkInFailedDesc: 'Riprova',
  },
  
  pt: {
    loading: 'Carregando...',
    invalidLink: 'Link inválido. Por favor use um link válido.',
    locationNotFound: 'Local não encontrado',
    loadFailed: 'Falha ao carregar',
    checkInTitle: 'Bem-vindo ao {businessName}!',
    checkInDescription: 'Check-in rápido - enviaremos um link após sua visita',
    checkInEmail: 'Email *',
    checkInEmailPlaceholder: 'seu@email.com',
    checkInName: 'Nome (opcional)',
    checkInNamePlaceholder: 'Seu nome',
    checkInButton: 'Check-in',
    checkingIn: 'Fazendo check-in...',
    checkInNote: 'Enviaremos um link por email após sua visita.',
    checkInCompleteTitle: 'Obrigado pelo check-in!',
    checkInCompleteMessage: 'Enviaremos um link para compartilhar sua experiência.',
    checkInCompleteTiming: 'O link será enviado em ~{hours} horas',
    checkInCompleteEnjoy: 'Aproveite sua visita! ✨',
    alreadyCheckedIn: 'Já registrado!',
    alreadyCheckedInMessage: 'Você já fez check-in hoje.',
    feedbackSubmittedTitle: 'Obrigado pelo seu feedback!',
    feedbackSubmittedMessage: 'Seu feedback nos ajuda a melhorar.',
    feedbackSubmittedNote: 'Nossa equipe revisará seu feedback.',
    howWasExperience: 'Como foi sua experiência?',
    tapToRate: 'Toque para avaliar',
    ratingExcellent: 'Excelente! 🎉',
    ratingGreat: 'Ótimo! 👍',
    ratingGood: 'Bom 😊',
    ratingFair: 'Regular 😐',
    ratingPoor: 'Ruim 😔',
    whatStoodOut: 'O que se destacou?',
    friendly: 'amigável',
    professional: 'profissional',
    enthusiastic: 'entusiasmado',
    yourReview: 'Sua avaliação',
    aiGenerated: 'Gerado por IA',
    generatingReview: 'Gerando sua avaliação...',
    reviewPlaceholder: 'Sua avaliação aparecerá aqui...',
    regenerateReview: 'Regenerar Avaliação',
    regenerating: 'Regenerando...',
    copyAndPost: 'Copiar e Postar no Google',
    copiedPaste: 'Copiado! Cole no Google',
    pasteHint: 'Pressione e segure no Google, depois "Colar"',
    submitFeedback: 'Enviar Feedback',
    submitting: 'Enviando...',
    feedbackNote: 'Seu feedback nos ajudará a melhorar',
    emailOptional: 'seu@email.com (opcional)',
    back: 'Voltar',
    next: 'Próximo',
    generating: 'Gerando...',
    selectRating: 'Por favor selecione uma avaliação',
    selectCharacteristics: 'Selecione características',
    selectCharacteristicsDesc: 'Selecione pelo menos um aspecto',
    commentGenerated: 'Comentário gerado!',
    commentGeneratedDesc: 'Edite antes de copiar',
    generationFailed: 'Falha na geração',
    generationFailedDesc: 'Tente novamente',
    noReviewToCopy: 'Nenhuma avaliação para copiar',
    noReviewToCopyDesc: 'Primeiro gere ou escreva uma avaliação',
    noGoogleLink: 'Sem link do Google',
    noGoogleLinkDesc: 'Este negócio não configurou o link do Google',
    reviewCopied: 'Avaliação copiada!',
    reviewCopiedDesc: 'Cole no formulário do Google',
    copyFailed: 'Cópia automática falhou',
    copyFailedDesc: 'Copie o texto manualmente',
    feedbackSubmitted: 'Feedback enviado',
    feedbackSubmittedDesc: 'Obrigado por compartilhar',
    submissionFailed: 'Falha no envio',
    submissionFailedDesc: 'Tente novamente',
    checkInFailed: 'Check-in falhou',
    checkInFailedDesc: 'Tente novamente',
  },
  
  // Simplified versions for remaining languages
  nl: {
    loading: 'Laden...',
    invalidLink: 'Ongeldige link.',
    locationNotFound: 'Locatie niet gevonden',
    loadFailed: 'Laden mislukt',
    checkInTitle: 'Welkom bij {businessName}!',
    checkInDescription: 'Snelle check-in - we sturen je later een link',
    checkInEmail: 'E-mail *',
    checkInEmailPlaceholder: 'jouw@email.com',
    checkInName: 'Naam (optioneel)',
    checkInNamePlaceholder: 'Jouw naam',
    checkInButton: 'Inchecken',
    checkingIn: 'Inchecken...',
    checkInNote: 'We sturen je een link per e-mail.',
    checkInCompleteTitle: 'Bedankt voor het inchecken!',
    checkInCompleteMessage: 'We sturen je later een link.',
    checkInCompleteTiming: 'Link wordt verzonden over ~{hours} uur',
    checkInCompleteEnjoy: 'Veel plezier! ✨',
    alreadyCheckedIn: 'Al ingecheckt!',
    alreadyCheckedInMessage: 'Je bent al ingecheckt vandaag.',
    feedbackSubmittedTitle: 'Bedankt voor je feedback!',
    feedbackSubmittedMessage: 'Je feedback helpt ons verbeteren.',
    feedbackSubmittedNote: 'Ons team zal je feedback bekijken.',
    howWasExperience: 'Hoe was je ervaring?',
    tapToRate: 'Tik om te beoordelen',
    ratingExcellent: 'Uitstekend! 🎉',
    ratingGreat: 'Geweldig! 👍',
    ratingGood: 'Goed 😊',
    ratingFair: 'Redelijk 😐',
    ratingPoor: 'Slecht 😔',
    whatStoodOut: 'Wat viel op?',
    friendly: 'vriendelijk',
    professional: 'professioneel',
    enthusiastic: 'enthousiast',
    yourReview: 'Jouw review',
    aiGenerated: 'AI-gegenereerd',
    generatingReview: 'Review genereren...',
    reviewPlaceholder: 'Je review verschijnt hier...',
    regenerateReview: 'Opnieuw genereren',
    regenerating: 'Genereren...',
    copyAndPost: 'Kopieer & Plaats op Google',
    copiedPaste: 'Gekopieerd! Plak in Google',
    pasteHint: 'Houd ingedrukt in Google, dan "Plakken"',
    submitFeedback: 'Feedback verzenden',
    submitting: 'Verzenden...',
    feedbackNote: 'Je feedback helpt ons verbeteren',
    emailOptional: 'jouw@email.com (optioneel)',
    back: 'Terug',
    next: 'Volgende',
    generating: 'Genereren...',
    selectRating: 'Selecteer een beoordeling',
    selectCharacteristics: 'Selecteer kenmerken',
    selectCharacteristicsDesc: 'Selecteer minimaal één aspect',
    commentGenerated: 'Commentaar gegenereerd!',
    commentGeneratedDesc: 'Bewerk voor het kopiëren',
    generationFailed: 'Genereren mislukt',
    generationFailedDesc: 'Probeer opnieuw',
    noReviewToCopy: 'Geen review om te kopiëren',
    noReviewToCopyDesc: 'Genereer eerst een review',
    noGoogleLink: 'Geen Google-link',
    noGoogleLinkDesc: 'Dit bedrijf heeft geen Google-link',
    reviewCopied: 'Review gekopieerd!',
    reviewCopiedDesc: 'Plak in Google',
    copyFailed: 'Automatisch kopiëren mislukt',
    copyFailedDesc: 'Kopieer handmatig',
    feedbackSubmitted: 'Feedback verzonden',
    feedbackSubmittedDesc: 'Bedankt',
    submissionFailed: 'Verzenden mislukt',
    submissionFailedDesc: 'Probeer opnieuw',
    checkInFailed: 'Inchecken mislukt',
    checkInFailedDesc: 'Probeer opnieuw',
  },
  
  pl: {
    loading: 'Ładowanie...',
    invalidLink: 'Nieprawidłowy link.',
    locationNotFound: 'Lokalizacja nie znaleziona',
    loadFailed: 'Błąd ładowania',
    checkInTitle: 'Witamy w {businessName}!',
    checkInDescription: 'Szybka rejestracja - wyślemy link po wizycie',
    checkInEmail: 'Email *',
    checkInEmailPlaceholder: 'twoj@email.com',
    checkInName: 'Imię (opcjonalne)',
    checkInNamePlaceholder: 'Twoje imię',
    checkInButton: 'Zarejestruj się',
    checkingIn: 'Rejestrowanie...',
    checkInNote: 'Wyślemy link emailem po wizycie.',
    checkInCompleteTitle: 'Dziękujemy za rejestrację!',
    checkInCompleteMessage: 'Wyślemy Ci link później.',
    checkInCompleteTiming: 'Link zostanie wysłany za ~{hours} godz',
    checkInCompleteEnjoy: 'Miłej wizyty! ✨',
    alreadyCheckedIn: 'Już zarejestrowany!',
    alreadyCheckedInMessage: 'Już się dzisiaj zarejestrowałeś.',
    feedbackSubmittedTitle: 'Dziękujemy za opinię!',
    feedbackSubmittedMessage: 'Twoja opinia pomaga nam się rozwijać.',
    feedbackSubmittedNote: 'Nasz zespół przejrzy Twoją opinię.',
    howWasExperience: 'Jak było Twoje doświadczenie?',
    tapToRate: 'Dotknij, aby ocenić',
    ratingExcellent: 'Doskonale! 🎉',
    ratingGreat: 'Świetnie! 👍',
    ratingGood: 'Dobrze 😊',
    ratingFair: 'Średnio 😐',
    ratingPoor: 'Słabo 😔',
    whatStoodOut: 'Co wyróżniło się?',
    friendly: 'przyjazny',
    professional: 'profesjonalny',
    enthusiastic: 'entuzjastyczny',
    yourReview: 'Twoja recenzja',
    aiGenerated: 'Wygenerowane przez AI',
    generatingReview: 'Generowanie recenzji...',
    reviewPlaceholder: 'Twoja recenzja pojawi się tutaj...',
    regenerateReview: 'Wygeneruj ponownie',
    regenerating: 'Generowanie...',
    copyAndPost: 'Skopiuj i opublikuj na Google',
    copiedPaste: 'Skopiowane! Wklej w Google',
    pasteHint: 'Przytrzymaj w Google, potem "Wklej"',
    submitFeedback: 'Wyślij opinię',
    submitting: 'Wysyłanie...',
    feedbackNote: 'Twoja opinia pomoże nam się poprawić',
    emailOptional: 'twoj@email.com (opcjonalne)',
    back: 'Wstecz',
    next: 'Dalej',
    generating: 'Generowanie...',
    selectRating: 'Wybierz ocenę',
    selectCharacteristics: 'Wybierz cechy',
    selectCharacteristicsDesc: 'Wybierz przynajmniej jeden aspekt',
    commentGenerated: 'Komentarz wygenerowany!',
    commentGeneratedDesc: 'Edytuj przed skopiowaniem',
    generationFailed: 'Generowanie nie powiodło się',
    generationFailedDesc: 'Spróbuj ponownie',
    noReviewToCopy: 'Brak recenzji do skopiowania',
    noReviewToCopyDesc: 'Najpierw wygeneruj recenzję',
    noGoogleLink: 'Brak linku Google',
    noGoogleLinkDesc: 'Ta firma nie ma linku Google',
    reviewCopied: 'Recenzja skopiowana!',
    reviewCopiedDesc: 'Wklej w Google',
    copyFailed: 'Automatyczne kopiowanie nie powiodło się',
    copyFailedDesc: 'Skopiuj ręcznie',
    feedbackSubmitted: 'Opinia wysłana',
    feedbackSubmittedDesc: 'Dziękujemy',
    submissionFailed: 'Wysyłanie nie powiodło się',
    submissionFailedDesc: 'Spróbuj ponownie',
    checkInFailed: 'Rejestracja nie powiodła się',
    checkInFailedDesc: 'Spróbuj ponownie',
  },
  
  // Placeholder for other languages - will use English fallback
  ru: { loading: 'Загрузка...', invalidLink: 'Неверная ссылка.', locationNotFound: 'Место не найдено', loadFailed: 'Ошибка загрузки', checkInTitle: 'Добро пожаловать в {businessName}!', checkInDescription: 'Быстрая регистрация', checkInEmail: 'Email *', checkInEmailPlaceholder: 'ваш@email.com', checkInName: 'Имя (необязательно)', checkInNamePlaceholder: 'Ваше имя', checkInButton: 'Зарегистрироваться', checkingIn: 'Регистрация...', checkInNote: 'Мы отправим ссылку на email.', checkInCompleteTitle: 'Спасибо за регистрацию!', checkInCompleteMessage: 'Мы отправим ссылку позже.', checkInCompleteTiming: 'Ссылка будет отправлена через ~{hours} часов', checkInCompleteEnjoy: 'Приятного визита! ✨', alreadyCheckedIn: 'Уже зарегистрированы!', alreadyCheckedInMessage: 'Вы уже зарегистрированы сегодня.', feedbackSubmittedTitle: 'Спасибо за отзыв!', feedbackSubmittedMessage: 'Ваш отзыв помогает нам улучшаться.', feedbackSubmittedNote: 'Наша команда рассмотрит ваш отзыв.', howWasExperience: 'Как прошёл ваш визит?', tapToRate: 'Нажмите для оценки', ratingExcellent: 'Отлично! 🎉', ratingGreat: 'Прекрасно! 👍', ratingGood: 'Хорошо 😊', ratingFair: 'Нормально 😐', ratingPoor: 'Плохо 😔', whatStoodOut: 'Что понравилось?', friendly: 'дружелюбный', professional: 'профессиональный', enthusiastic: 'восторженный', yourReview: 'Ваш отзыв', aiGenerated: 'Создано ИИ', generatingReview: 'Генерация отзыва...', reviewPlaceholder: 'Ваш отзыв появится здесь...', regenerateReview: 'Сгенерировать заново', regenerating: 'Генерация...', copyAndPost: 'Скопировать и опубликовать в Google', copiedPaste: 'Скопировано! Вставьте в Google', pasteHint: 'Удерживайте в Google, затем "Вставить"', submitFeedback: 'Отправить отзыв', submitting: 'Отправка...', feedbackNote: 'Ваш отзыв поможет нам улучшиться', emailOptional: 'ваш@email.com (необязательно)', back: 'Назад', next: 'Далее', generating: 'Генерация...', selectRating: 'Выберите оценку', selectCharacteristics: 'Выберите характеристики', selectCharacteristicsDesc: 'Выберите хотя бы один аспект', commentGenerated: 'Комментарий создан!', commentGeneratedDesc: 'Отредактируйте перед копированием', generationFailed: 'Ошибка генерации', generationFailedDesc: 'Попробуйте снова', noReviewToCopy: 'Нет отзыва для копирования', noReviewToCopyDesc: 'Сначала создайте отзыв', noGoogleLink: 'Нет ссылки Google', noGoogleLinkDesc: 'У этого бизнеса нет ссылки Google', reviewCopied: 'Отзыв скопирован!', reviewCopiedDesc: 'Вставьте в Google', copyFailed: 'Автокопирование не удалось', copyFailedDesc: 'Скопируйте вручную', feedbackSubmitted: 'Отзыв отправлен', feedbackSubmittedDesc: 'Спасибо', submissionFailed: 'Ошибка отправки', submissionFailedDesc: 'Попробуйте снова', checkInFailed: 'Ошибка регистрации', checkInFailedDesc: 'Попробуйте снова' },
  
  zh: { loading: '加载中...', invalidLink: '无效链接', locationNotFound: '未找到位置', loadFailed: '加载失败', checkInTitle: '欢迎来到{businessName}!', checkInDescription: '快速签到 - 我们稍后发送评价链接', checkInEmail: '邮箱 *', checkInEmailPlaceholder: 'your@email.com', checkInName: '姓名 (可选)', checkInNamePlaceholder: '您的姓名', checkInButton: '签到', checkingIn: '签到中...', checkInNote: '访问后我们会发送评价链接。', checkInCompleteTitle: '感谢签到!', checkInCompleteMessage: '稍后发送链接。', checkInCompleteTiming: '链接将在~{hours}小时后发送', checkInCompleteEnjoy: '祝您愉快! ✨', alreadyCheckedIn: '已签到!', alreadyCheckedInMessage: '您今天已签到。', feedbackSubmittedTitle: '感谢反馈!', feedbackSubmittedMessage: '您的反馈帮助我们改进。', feedbackSubmittedNote: '我们会查看您的反馈。', howWasExperience: '您的体验如何?', tapToRate: '点击评分', ratingExcellent: '非常好! 🎉', ratingGreat: '很好! 👍', ratingGood: '好 😊', ratingFair: '一般 😐', ratingPoor: '差 😔', whatStoodOut: '什么让您印象深刻? (可选)', friendly: '友好', professional: '专业', enthusiastic: '热情', yourReview: '您的评价', aiGenerated: 'AI生成', generatingReview: '正在生成评价...', reviewPlaceholder: '您的评价将显示在这里...', regenerateReview: '重新生成', regenerating: '生成中...', copyAndPost: '复制并发布到Google', copiedPaste: '已复制! 粘贴到Google', pasteHint: '在Google中长按，然后"粘贴"', submitFeedback: '提交反馈', submitting: '提交中...', feedbackNote: '您的反馈帮助我们改进', emailOptional: 'your@email.com (可选)', back: '返回', next: '下一步', generating: '生成中...', selectRating: '请选择评分', selectCharacteristics: '选择特点', selectCharacteristicsDesc: '请选择至少一个方面', commentGenerated: '评论已生成!', commentGeneratedDesc: '复制前可编辑', generationFailed: '生成失败', generationFailedDesc: '请重试', noReviewToCopy: '没有评价可复制', noReviewToCopyDesc: '请先生成评价', noGoogleLink: '没有Google链接', noGoogleLinkDesc: '此商家未设置Google链接', reviewCopied: '评价已复制!', reviewCopiedDesc: '粘贴到Google', copyFailed: '自动复制失败', copyFailedDesc: '请手动复制', feedbackSubmitted: '反馈已提交', feedbackSubmittedDesc: '谢谢', submissionFailed: '提交失败', submissionFailedDesc: '请重试', checkInFailed: '签到失败', checkInFailedDesc: '请重试' },
  
  ja: { loading: '読み込み中...', invalidLink: '無効なリンクです。', locationNotFound: '場所が見つかりません', loadFailed: '読み込みに失敗しました', checkInTitle: '{businessName}へようこそ!', checkInDescription: 'クイックチェックイン - 後でリンクを送ります', checkInEmail: 'メール *', checkInEmailPlaceholder: 'your@email.com', checkInName: '名前 (任意)', checkInNamePlaceholder: 'お名前', checkInButton: 'チェックイン', checkingIn: 'チェックイン中...', checkInNote: '訪問後にリンクをメールで送ります。', checkInCompleteTitle: 'チェックインありがとうございます!', checkInCompleteMessage: '後でリンクを送ります。', checkInCompleteTiming: 'リンクは約{hours}時間後に送信されます', checkInCompleteEnjoy: '楽しんでください! ✨', alreadyCheckedIn: 'すでにチェックイン済み!', alreadyCheckedInMessage: '今日はすでにチェックインしています。', feedbackSubmittedTitle: 'ご意見ありがとうございます!', feedbackSubmittedMessage: 'ご意見は改善に役立ちます。', feedbackSubmittedNote: 'スタッフがご意見を確認します。', howWasExperience: 'ご体験はいかがでしたか?', tapToRate: 'タップして評価', ratingExcellent: '最高! 🎉', ratingGreat: '素晴らしい! 👍', ratingGood: '良い 😊', ratingFair: '普通 😐', ratingPoor: '悪い 😔', whatStoodOut: '印象に残ったことは? (任意)', friendly: 'フレンドリー', professional: 'プロフェッショナル', enthusiastic: '熱心', yourReview: 'レビュー', aiGenerated: 'AI生成', generatingReview: 'レビューを生成中...', reviewPlaceholder: 'レビューがここに表示されます...', regenerateReview: '再生成', regenerating: '生成中...', copyAndPost: 'コピーしてGoogleに投稿', copiedPaste: 'コピー完了! Googleに貼り付け', pasteHint: 'Googleで長押しして「貼り付け」', submitFeedback: 'フィードバックを送信', submitting: '送信中...', feedbackNote: 'ご意見は改善に役立ちます', emailOptional: 'your@email.com (任意)', back: '戻る', next: '次へ', generating: '生成中...', selectRating: '評価を選択してください', selectCharacteristics: '特徴を選択', selectCharacteristicsDesc: '少なくとも1つ選択してください', commentGenerated: 'コメント生成完了!', commentGeneratedDesc: 'コピー前に編集可能', generationFailed: '生成に失敗しました', generationFailedDesc: '再試行してください', noReviewToCopy: 'コピーするレビューがありません', noReviewToCopyDesc: '先にレビューを生成してください', noGoogleLink: 'Googleリンクがありません', noGoogleLinkDesc: 'この店舗はGoogleリンク未設定です', reviewCopied: 'レビューをコピーしました!', reviewCopiedDesc: 'Googleに貼り付けてください', copyFailed: '自動コピーに失敗しました', copyFailedDesc: '手動でコピーしてください', feedbackSubmitted: 'フィードバック送信完了', feedbackSubmittedDesc: 'ありがとうございます', submissionFailed: '送信に失敗しました', submissionFailedDesc: '再試行してください', checkInFailed: 'チェックインに失敗しました', checkInFailedDesc: '再試行してください' },
  
  ko: { loading: '로딩 중...', invalidLink: '잘못된 링크입니다.', locationNotFound: '위치를 찾을 수 없습니다', loadFailed: '로딩 실패', checkInTitle: '{businessName}에 오신 것을 환영합니다!', checkInDescription: '빠른 체크인 - 나중에 링크를 보내드립니다', checkInEmail: '이메일 *', checkInEmailPlaceholder: 'your@email.com', checkInName: '이름 (선택)', checkInNamePlaceholder: '이름', checkInButton: '체크인', checkingIn: '체크인 중...', checkInNote: '방문 후 이메일로 링크를 보내드립니다.', checkInCompleteTitle: '체크인 감사합니다!', checkInCompleteMessage: '나중에 링크를 보내드립니다.', checkInCompleteTiming: '링크는 약 {hours}시간 후에 전송됩니다', checkInCompleteEnjoy: '즐거운 시간 되세요! ✨', alreadyCheckedIn: '이미 체크인됨!', alreadyCheckedInMessage: '오늘 이미 체크인하셨습니다.', feedbackSubmittedTitle: '피드백 감사합니다!', feedbackSubmittedMessage: '피드백이 개선에 도움이 됩니다.', feedbackSubmittedNote: '팀에서 피드백을 검토합니다.', howWasExperience: '경험은 어떠셨나요?', tapToRate: '탭하여 평가', ratingExcellent: '최고! 🎉', ratingGreat: '좋아요! 👍', ratingGood: '좋음 😊', ratingFair: '보통 😐', ratingPoor: '나쁨 😔', whatStoodOut: '어떤 점이 좋았나요? (선택)', friendly: '친근한', professional: '전문적인', enthusiastic: '열정적인', yourReview: '리뷰', aiGenerated: 'AI 생성', generatingReview: '리뷰 생성 중...', reviewPlaceholder: '리뷰가 여기에 표시됩니다...', regenerateReview: '다시 생성', regenerating: '생성 중...', copyAndPost: '복사하고 Google에 게시', copiedPaste: '복사됨! Google에 붙여넣기', pasteHint: 'Google에서 길게 누르고 "붙여넣기"', submitFeedback: '피드백 제출', submitting: '제출 중...', feedbackNote: '피드백이 개선에 도움이 됩니다', emailOptional: 'your@email.com (선택)', back: '뒤로', next: '다음', generating: '생성 중...', selectRating: '평점을 선택하세요', selectCharacteristics: '특징 선택', selectCharacteristicsDesc: '최소 하나를 선택하세요', commentGenerated: '댓글 생성됨!', commentGeneratedDesc: '복사 전 편집 가능', generationFailed: '생성 실패', generationFailedDesc: '다시 시도하세요', noReviewToCopy: '복사할 리뷰가 없습니다', noReviewToCopyDesc: '먼저 리뷰를 생성하세요', noGoogleLink: 'Google 링크 없음', noGoogleLinkDesc: '이 업체는 Google 링크가 없습니다', reviewCopied: '리뷰 복사됨!', reviewCopiedDesc: 'Google에 붙여넣으세요', copyFailed: '자동 복사 실패', copyFailedDesc: '수동으로 복사하세요', feedbackSubmitted: '피드백 제출됨', feedbackSubmittedDesc: '감사합니다', submissionFailed: '제출 실패', submissionFailedDesc: '다시 시도하세요', checkInFailed: '체크인 실패', checkInFailedDesc: '다시 시도하세요' },
  
  ar: { loading: 'جاري التحميل...', invalidLink: 'رابط غير صالح.', locationNotFound: 'الموقع غير موجود', loadFailed: 'فشل التحميل', checkInTitle: 'مرحباً بك في {businessName}!', checkInDescription: 'تسجيل سريع - سنرسل لك الرابط لاحقاً', checkInEmail: 'البريد الإلكتروني *', checkInEmailPlaceholder: 'your@email.com', checkInName: 'الاسم (اختياري)', checkInNamePlaceholder: 'اسمك', checkInButton: 'تسجيل الدخول', checkingIn: 'جاري التسجيل...', checkInNote: 'سنرسل لك رابطاً بعد زيارتك.', checkInCompleteTitle: 'شكراً للتسجيل!', checkInCompleteMessage: 'سنرسل لك الرابط لاحقاً.', checkInCompleteTiming: 'سيتم إرسال الرابط خلال ~{hours} ساعات', checkInCompleteEnjoy: 'استمتع بزيارتك! ✨', alreadyCheckedIn: 'مسجل بالفعل!', alreadyCheckedInMessage: 'لقد سجلت اليوم بالفعل.', feedbackSubmittedTitle: 'شكراً على ملاحظاتك!', feedbackSubmittedMessage: 'ملاحظاتك تساعدنا على التحسين.', feedbackSubmittedNote: 'سيراجع فريقنا ملاحظاتك.', howWasExperience: 'كيف كانت تجربتك؟', tapToRate: 'انقر للتقييم', ratingExcellent: 'ممتاز! 🎉', ratingGreat: 'رائع! 👍', ratingGood: 'جيد 😊', ratingFair: 'مقبول 😐', ratingPoor: 'سيء 😔', whatStoodOut: 'ما الذي برز؟ (اختياري)', friendly: 'ودود', professional: 'احترافي', enthusiastic: 'متحمس', yourReview: 'تقييمك', aiGenerated: 'تم إنشاؤه بالذكاء الاصطناعي', generatingReview: 'جاري إنشاء التقييم...', reviewPlaceholder: 'سيظهر تقييمك هنا...', regenerateReview: 'إعادة الإنشاء', regenerating: 'جاري الإنشاء...', copyAndPost: 'نسخ ونشر على Google', copiedPaste: 'تم النسخ! الصق في Google', pasteHint: 'اضغط مطولاً في Google ثم "لصق"', submitFeedback: 'إرسال الملاحظات', submitting: 'جاري الإرسال...', feedbackNote: 'ملاحظاتك ستساعدنا على التحسين', emailOptional: 'your@email.com (اختياري)', back: 'رجوع', next: 'التالي', generating: 'جاري الإنشاء...', selectRating: 'يرجى اختيار تقييم', selectCharacteristics: 'اختر الخصائص', selectCharacteristicsDesc: 'يرجى اختيار جانب واحد على الأقل', commentGenerated: 'تم إنشاء التعليق!', commentGeneratedDesc: 'يمكنك التعديل قبل النسخ', generationFailed: 'فشل الإنشاء', generationFailedDesc: 'حاول مرة أخرى', noReviewToCopy: 'لا يوجد تقييم للنسخ', noReviewToCopyDesc: 'يرجى إنشاء تقييم أولاً', noGoogleLink: 'لا يوجد رابط Google', noGoogleLinkDesc: 'هذا العمل ليس لديه رابط Google', reviewCopied: 'تم نسخ التقييم!', reviewCopiedDesc: 'الصقه في Google', copyFailed: 'فشل النسخ التلقائي', copyFailedDesc: 'انسخ يدوياً', feedbackSubmitted: 'تم إرسال الملاحظات', feedbackSubmittedDesc: 'شكراً', submissionFailed: 'فشل الإرسال', submissionFailedDesc: 'حاول مرة أخرى', checkInFailed: 'فشل التسجيل', checkInFailedDesc: 'حاول مرة أخرى' },
  
  hi: { loading: 'लोड हो रहा है...', invalidLink: 'अमान्य लिंक।', locationNotFound: 'स्थान नहीं मिला', loadFailed: 'लोड करने में विफल', checkInTitle: '{businessName} में आपका स्वागत है!', checkInDescription: 'त्वरित चेक-इन - हम बाद में लिंक भेजेंगे', checkInEmail: 'ईमेल *', checkInEmailPlaceholder: 'your@email.com', checkInName: 'नाम (वैकल्पिक)', checkInNamePlaceholder: 'आपका नाम', checkInButton: 'चेक इन', checkingIn: 'चेक इन हो रहा है...', checkInNote: 'विज़िट के बाद हम ईमेल द्वारा लिंक भेजेंगे।', checkInCompleteTitle: 'चेक-इन के लिए धन्यवाद!', checkInCompleteMessage: 'हम बाद में लिंक भेजेंगे।', checkInCompleteTiming: 'लिंक ~{hours} घंटे में भेजा जाएगा', checkInCompleteEnjoy: 'अपनी विज़िट का आनंद लें! ✨', alreadyCheckedIn: 'पहले से चेक इन!', alreadyCheckedInMessage: 'आप आज पहले ही चेक इन कर चुके हैं।', feedbackSubmittedTitle: 'आपकी प्रतिक्रिया के लिए धन्यवाद!', feedbackSubmittedMessage: 'आपकी प्रतिक्रिया हमें सुधारने में मदद करती है।', feedbackSubmittedNote: 'हमारी टीम आपकी प्रतिक्रिया की समीक्षा करेगी।', howWasExperience: 'आपका अनुभव कैसा रहा?', tapToRate: 'रेट करने के लिए टैप करें', ratingExcellent: 'उत्कृष्ट! 🎉', ratingGreat: 'बहुत अच्छा! 👍', ratingGood: 'अच्छा 😊', ratingFair: 'ठीक 😐', ratingPoor: 'खराब 😔', whatStoodOut: 'क्या खास लगा? (वैकल्पिक)', friendly: 'मैत्रीपूर्ण', professional: 'पेशेवर', enthusiastic: 'उत्साही', yourReview: 'आपकी समीक्षा', aiGenerated: 'AI द्वारा निर्मित', generatingReview: 'समीक्षा बनाई जा रही है...', reviewPlaceholder: 'आपकी समीक्षा यहां दिखाई देगी...', regenerateReview: 'पुनः उत्पन्न करें', regenerating: 'उत्पन्न हो रहा है...', copyAndPost: 'कॉपी करें और Google पर पोस्ट करें', copiedPaste: 'कॉपी हो गया! Google में पेस्ट करें', pasteHint: 'Google में लंबे समय तक दबाएं, फिर "पेस्ट"', submitFeedback: 'प्रतिक्रिया भेजें', submitting: 'भेजा जा रहा है...', feedbackNote: 'आपकी प्रतिक्रिया सुधार में मदद करेगी', emailOptional: 'your@email.com (वैकल्पिक)', back: 'वापस', next: 'आगे', generating: 'उत्पन्न हो रहा है...', selectRating: 'कृपया रेटिंग चुनें', selectCharacteristics: 'विशेषताएं चुनें', selectCharacteristicsDesc: 'कम से कम एक पहलू चुनें', commentGenerated: 'टिप्पणी बनाई गई!', commentGeneratedDesc: 'कॉपी करने से पहले संपादित करें', generationFailed: 'उत्पन्न करने में विफल', generationFailedDesc: 'पुनः प्रयास करें', noReviewToCopy: 'कॉपी करने के लिए कोई समीक्षा नहीं', noReviewToCopyDesc: 'पहले समीक्षा बनाएं', noGoogleLink: 'कोई Google लिंक नहीं', noGoogleLinkDesc: 'इस व्यवसाय में Google लिंक नहीं है', reviewCopied: 'समीक्षा कॉपी हो गई!', reviewCopiedDesc: 'Google में पेस्ट करें', copyFailed: 'स्वचालित कॉपी विफल', copyFailedDesc: 'मैन्युअल रूप से कॉपी करें', feedbackSubmitted: 'प्रतिक्रिया भेजी गई', feedbackSubmittedDesc: 'धन्यवाद', submissionFailed: 'भेजने में विफल', submissionFailedDesc: 'पुनः प्रयास करें', checkInFailed: 'चेक-इन विफल', checkInFailedDesc: 'पुनः प्रयास करें' },
  
  th: { loading: 'กำลังโหลด...', invalidLink: 'ลิงก์ไม่ถูกต้อง', locationNotFound: 'ไม่พบสถานที่', loadFailed: 'โหลดล้มเหลว', checkInTitle: 'ยินดีต้อนรับสู่ {businessName}!', checkInDescription: 'เช็คอินด่วน - เราจะส่งลิงก์ให้ภายหลัง', checkInEmail: 'อีเมล *', checkInEmailPlaceholder: 'your@email.com', checkInName: 'ชื่อ (ไม่บังคับ)', checkInNamePlaceholder: 'ชื่อของคุณ', checkInButton: 'เช็คอิน', checkingIn: 'กำลังเช็คอิน...', checkInNote: 'เราจะส่งลิงก์ทางอีเมลหลังจากเยี่ยมชม', checkInCompleteTitle: 'ขอบคุณสำหรับการเช็คอิน!', checkInCompleteMessage: 'เราจะส่งลิงก์ให้ภายหลัง', checkInCompleteTiming: 'ลิงก์จะถูกส่งใน ~{hours} ชั่วโมง', checkInCompleteEnjoy: 'ขอให้สนุก! ✨', alreadyCheckedIn: 'เช็คอินแล้ว!', alreadyCheckedInMessage: 'คุณเช็คอินวันนี้แล้ว', feedbackSubmittedTitle: 'ขอบคุณสำหรับความคิดเห็น!', feedbackSubmittedMessage: 'ความคิดเห็นของคุณช่วยเราปรับปรุง', feedbackSubmittedNote: 'ทีมงานจะตรวจสอบความคิดเห็นของคุณ', howWasExperience: 'ประสบการณ์ของคุณเป็นอย่างไร?', tapToRate: 'แตะเพื่อให้คะแนน', ratingExcellent: 'ยอดเยี่ยม! 🎉', ratingGreat: 'ดีมาก! 👍', ratingGood: 'ดี 😊', ratingFair: 'พอใช้ 😐', ratingPoor: 'แย่ 😔', whatStoodOut: 'อะไรโดดเด่น? (ไม่บังคับ)', friendly: 'เป็นมิตร', professional: 'มืออาชีพ', enthusiastic: 'กระตือรือร้น', yourReview: 'รีวิวของคุณ', aiGenerated: 'สร้างโดย AI', generatingReview: 'กำลังสร้างรีวิว...', reviewPlaceholder: 'รีวิวของคุณจะปรากฏที่นี่...', regenerateReview: 'สร้างใหม่', regenerating: 'กำลังสร้าง...', copyAndPost: 'คัดลอกและโพสต์บน Google', copiedPaste: 'คัดลอกแล้ว! วางใน Google', pasteHint: 'กดค้างใน Google แล้ว "วาง"', submitFeedback: 'ส่งความคิดเห็น', submitting: 'กำลังส่ง...', feedbackNote: 'ความคิดเห็นของคุณจะช่วยเราปรับปรุง', emailOptional: 'your@email.com (ไม่บังคับ)', back: 'กลับ', next: 'ถัดไป', generating: 'กำลังสร้าง...', selectRating: 'กรุณาเลือกคะแนน', selectCharacteristics: 'เลือกคุณสมบัติ', selectCharacteristicsDesc: 'กรุณาเลือกอย่างน้อยหนึ่งด้าน', commentGenerated: 'สร้างความคิดเห็นแล้ว!', commentGeneratedDesc: 'แก้ไขก่อนคัดลอก', generationFailed: 'สร้างล้มเหลว', generationFailedDesc: 'ลองอีกครั้ง', noReviewToCopy: 'ไม่มีรีวิวให้คัดลอก', noReviewToCopyDesc: 'กรุณาสร้างรีวิวก่อน', noGoogleLink: 'ไม่มีลิงก์ Google', noGoogleLinkDesc: 'ธุรกิจนี้ไม่มีลิงก์ Google', reviewCopied: 'คัดลอกรีวิวแล้ว!', reviewCopiedDesc: 'วางใน Google', copyFailed: 'คัดลอกอัตโนมัติล้มเหลว', copyFailedDesc: 'คัดลอกด้วยตนเอง', feedbackSubmitted: 'ส่งความคิดเห็นแล้ว', feedbackSubmittedDesc: 'ขอบคุณ', submissionFailed: 'ส่งล้มเหลว', submissionFailedDesc: 'ลองอีกครั้ง', checkInFailed: 'เช็คอินล้มเหลว', checkInFailedDesc: 'ลองอีกครั้ง' },
  
  vi: { loading: 'Đang tải...', invalidLink: 'Liên kết không hợp lệ.', locationNotFound: 'Không tìm thấy địa điểm', loadFailed: 'Tải thất bại', checkInTitle: 'Chào mừng đến {businessName}!', checkInDescription: 'Check-in nhanh - chúng tôi sẽ gửi link sau', checkInEmail: 'Email *', checkInEmailPlaceholder: 'your@email.com', checkInName: 'Tên (tùy chọn)', checkInNamePlaceholder: 'Tên của bạn', checkInButton: 'Check-in', checkingIn: 'Đang check-in...', checkInNote: 'Chúng tôi sẽ gửi link qua email sau khi bạn ghé thăm.', checkInCompleteTitle: 'Cảm ơn bạn đã check-in!', checkInCompleteMessage: 'Chúng tôi sẽ gửi link sau.', checkInCompleteTiming: 'Link sẽ được gửi trong ~{hours} giờ', checkInCompleteEnjoy: 'Chúc bạn vui vẻ! ✨', alreadyCheckedIn: 'Đã check-in!', alreadyCheckedInMessage: 'Bạn đã check-in hôm nay rồi.', feedbackSubmittedTitle: 'Cảm ơn phản hồi của bạn!', feedbackSubmittedMessage: 'Phản hồi của bạn giúp chúng tôi cải thiện.', feedbackSubmittedNote: 'Đội ngũ sẽ xem xét phản hồi của bạn.', howWasExperience: 'Trải nghiệm của bạn thế nào?', tapToRate: 'Nhấn để đánh giá', ratingExcellent: 'Tuyệt vời! 🎉', ratingGreat: 'Rất tốt! 👍', ratingGood: 'Tốt 😊', ratingFair: 'Bình thường 😐', ratingPoor: 'Tệ 😔', whatStoodOut: 'Điều gì nổi bật? (tùy chọn)', friendly: 'thân thiện', professional: 'chuyên nghiệp', enthusiastic: 'nhiệt tình', yourReview: 'Đánh giá của bạn', aiGenerated: 'Tạo bởi AI', generatingReview: 'Đang tạo đánh giá...', reviewPlaceholder: 'Đánh giá của bạn sẽ xuất hiện ở đây...', regenerateReview: 'Tạo lại', regenerating: 'Đang tạo...', copyAndPost: 'Sao chép và đăng lên Google', copiedPaste: 'Đã sao chép! Dán vào Google', pasteHint: 'Nhấn giữ trong Google, rồi "Dán"', submitFeedback: 'Gửi phản hồi', submitting: 'Đang gửi...', feedbackNote: 'Phản hồi của bạn sẽ giúp chúng tôi cải thiện', emailOptional: 'your@email.com (tùy chọn)', back: 'Quay lại', next: 'Tiếp', generating: 'Đang tạo...', selectRating: 'Vui lòng chọn đánh giá', selectCharacteristics: 'Chọn đặc điểm', selectCharacteristicsDesc: 'Vui lòng chọn ít nhất một khía cạnh', commentGenerated: 'Đã tạo bình luận!', commentGeneratedDesc: 'Chỉnh sửa trước khi sao chép', generationFailed: 'Tạo thất bại', generationFailedDesc: 'Thử lại', noReviewToCopy: 'Không có đánh giá để sao chép', noReviewToCopyDesc: 'Vui lòng tạo đánh giá trước', noGoogleLink: 'Không có liên kết Google', noGoogleLinkDesc: 'Doanh nghiệp này chưa có liên kết Google', reviewCopied: 'Đã sao chép đánh giá!', reviewCopiedDesc: 'Dán vào Google', copyFailed: 'Sao chép tự động thất bại', copyFailedDesc: 'Sao chép thủ công', feedbackSubmitted: 'Đã gửi phản hồi', feedbackSubmittedDesc: 'Cảm ơn', submissionFailed: 'Gửi thất bại', submissionFailedDesc: 'Thử lại', checkInFailed: 'Check-in thất bại', checkInFailedDesc: 'Thử lại' },
};

export function detectLanguage(): SupportedLanguage {
  // Check URL parameter first
  const urlParams = new URLSearchParams(window.location.search);
  const langParam = urlParams.get('lang');
  if (langParam && languageMap[langParam]) {
    return languageMap[langParam];
  }
  
  // Check browser language
  const browserLang = navigator.language || (navigator as any).userLanguage || 'en';
  
  // Try exact match first
  if (languageMap[browserLang]) {
    return languageMap[browserLang];
  }
  
  // Try language code without region (e.g., 'en' from 'en-US')
  const langCode = browserLang.split('-')[0];
  if (languageMap[langCode]) {
    return languageMap[langCode];
  }
  
  // Default to English
  return 'en';
}

export function useLanguageDetection() {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  
  useEffect(() => {
    const detected = detectLanguage();
    setLanguage(detected);
  }, []);
  
  const t = (key: string, replacements?: Record<string, string>): string => {
    let text = translations[language]?.[key] || translations['en'][key] || key;
    
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        text = text.replace(`{${placeholder}}`, value);
      });
    }
    
    return text;
  };
  
  return { language, setLanguage, t };
}
