// Single source of truth for AiLys Agency branding.
export const APP_CONFIG = {
  name: 'AiLys',
  fullName: 'AiLys Agency',
  tagline: 'LLM Visibility & Optimization, made in Québec.',
  description: 'AiLys Agency is a Québec-based AI search reputation agency. We get local businesses cited by ChatGPT, Perplexity, Claude, Gemini, Google AIO and Bing Copilot through AEO, GEO and E-E-A-T work.',
  url: 'https://www.ailysagency.ca',
  urlAlt: 'https://www.ailysagency.com',
  logo: '/ailys-logo.svg',
  icon: '/ailys-icon.svg',
  email: 'hello@ailysagency.ca',
  origin: 'Québec, Canada',
  twitterHandle: '@ailysagency',
  keywords: [
    'AiLys',
    'AiLys Agency',
    'LLM visibility',
    'AEO',
    'GEO',
    'E-E-A-T',
    'AI search optimization',
    'ChatGPT visibility',
    'Perplexity citations',
    'Google AI Overviews',
    'Bing Copilot',
    'agence visibilité IA Québec',
    'Quebec AI agency',
    'local business AI search',
    'Google Business Profile management',
  ],
} as const;
