// Export action plan to Notion / Google Docs / clipboard / email.
//
// All client-side. No server roundtrip needed.
//   - Notion: opens new Notion page via web URL (user pastes manually as block)
//   - Google Docs: opens a pre-filled Docs URL with the content as a query param
//   - Clipboard: navigator.clipboard.writeText
//   - Email: mailto: with subject + body
//
// Long-term path (when Phase B.4 ships): server-rendered branded PDF as
// downloadable file + email attachment.

import { useState } from "react";
import {
  FileText,
  ClipboardCheck,
  Mail,
  Copy,
  Check,
  Send,
} from "lucide-react";

interface Props {
  businessName: string;
  city: string;
  actionPlan: string;
  score: number;
}

function formatPlanText(props: Props): string {
  return `AiLys AI Visibility Audit · 90-day Action Plan
Business: ${props.businessName}
City: ${props.city}
Score: ${props.score} / 100
Generated: ${new Date().toLocaleDateString()}

----

${props.actionPlan}

----

Generated by AiLys Agency · https://www.ailysagency.ca
Run a fresh audit anytime: https://www.ailysagency.ca/audit
`;
}

export function ExportActionPlan(props: Props) {
  const [copied, setCopied] = useState(false);
  const text = formatPlanText(props);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {
      // ignore
    }
  };

  const mailToHref = `mailto:?subject=${encodeURIComponent(
    `90-day AI Visibility Action Plan for ${props.businessName}`,
  )}&body=${encodeURIComponent(text)}`;

  // Notion's web import doesn't take a URL param for raw text yet, so we open
  // the Notion new-page URL and copy to clipboard simultaneously. The user
  // pastes once landed.
  const handleNotion = async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // ignore
    }
    window.open("https://www.notion.so/new", "_blank", "noopener,noreferrer");
  };

  // Google Docs: same pattern. Open new doc, copy text to clipboard.
  const handleGoogleDoc = async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // ignore
    }
    window.open(
      "https://docs.google.com/document/create",
      "_blank",
      "noopener,noreferrer",
    );
  };

  return (
    <div className="rounded-2xl border border-border/40 bg-card/30 backdrop-blur-md p-6">
      <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-primary mb-2 inline-flex items-center gap-1.5">
        <Send className="w-3.5 h-3.5" />
        Export action plan
      </div>
      <h4 className="font-display text-lg sm:text-xl mb-2 leading-tight">
        Send to your tool of choice.
      </h4>
      <p className="text-xs text-muted-foreground mb-4 max-w-prose">
        We do not require any account. We copy the formatted plan to your
        clipboard, then open the new-document URL of your tool. Paste once
        landed.
      </p>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">
        <button
          type="button"
          onClick={handleNotion}
          className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-full border border-border/40 hover:border-primary/40 text-xs font-medium transition-colors"
        >
          <FileText className="w-3.5 h-3.5" />
          Notion
        </button>
        <button
          type="button"
          onClick={handleGoogleDoc}
          className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-full border border-border/40 hover:border-primary/40 text-xs font-medium transition-colors"
        >
          <ClipboardCheck className="w-3.5 h-3.5" />
          Google Doc
        </button>
        <a
          href={mailToHref}
          className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-full border border-border/40 hover:border-primary/40 text-xs font-medium transition-colors"
        >
          <Mail className="w-3.5 h-3.5" />
          Email
        </a>
        <button
          type="button"
          onClick={handleCopy}
          className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-full border border-border/40 hover:border-primary/40 text-xs font-medium transition-colors"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              Copied
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              Copy
            </>
          )}
        </button>
      </div>
    </div>
  );
}
